### PR TITLE
Code Review: Documentation to plugin authors on how to support the new system (#12070)

### PR DESCRIPTION
**Pull request by SheffieldKevin**
Code review for Documentation to plugin authors on how to support the new system (#12070):

Connect to BohemianCoding/Sketch#12070.

### CODE REVIEW

**Comment by bomberstudios** [comment]
I have no idea why there's so much code in this PR. I have created a new branch (`feature/12070`) and cherry-picked the relevant commits (see https://github.com/BohemianCoding/developer.sketchapp.com/compare/feature/12070?expand=1) so if you're ok with that, can we close this PR and open a new one based off `feature/12070`?

**Comment by SheffieldKevin** [comment]
That looks fine to me @bomberstudios

**Comment by bomberstudios** [comment]
Closing this one, then

**Comment by samdeane** [comment]
I'm a little concerned that you may be merging to/from the wrong place. And/or that gh-pages may not be using the right version of the website.

**Comment by bomberstudios** [comment]
You're right, and I'm 99% sure I've broken something on the site. I'll take a look to make sure everything is working as it should be…

**Pull request closed without merging**
