### PR TITLE
Code Review: Implement unit tests for the JS API (#10090)

### PR DESCRIPTION
**Pull request by samdeane**
Code review for Implement unit tests for the JS API (#10090):

> Issue #8201 has supplied a simple unit testing framework that we can use to test the JS API.
> 
> Now we need to actually fill in the tests...

Connect to BohemianCoding/Sketch#10090.

### CODE REVIEW

**Comment by samdeane** [comment]
Why not let @bomberstudios review it? There's not much point in having a review process if you're just going to wave things through...

**Comment by pieteromvlee** [comment]
Well, it's gigantic and most of the stuff seems like noise...

**Comment by samdeane** [comment]
Ah, right, you just mean this PR and not the whole issue.

Most of this PR is probably the *compiled version* of the SketchAPI changes - which as we've discussed before, should be ignored and reviewed instead in the SketchAPI repo. 

If there are other changes in here though (I can't honestly remember), then it would be better to review them.

**Comment by pieteromvlee** [comment]
I did review all the other sub modules proper yes.

**Pull request merged**
